name: smooth-loader

services:
    app:
        image: smooth-loader
        container_name: smooth-loader
        build:
            context: .
            dockerfile: Containerfile
        volumes:
            - .:/app:z
